---
- name: "Copy VSCode extensions to target host"
  copy:
    src: "extensions/{{ item }}"
    dest: /tmp
  loop:
    - "{{ playwright_extension }}"
    - "{{ redhat_ansible_extension }}"
    - "{{ redhat_yaml_extension }}"
  # loop:
  #   - "{{ list_of_extensions }}"

- name: "Install VSCode extensions for {{ target_user }} user"
  command: "code --install-extension /tmp/{{ item }}"
  become: true
  become_user: "{{ target_user }}"
  loop:
    - "{{ playwright_extension }}"
    - "{{ redhat_ansible_extension }}"
    - "{{ redhat_yaml_extension }}"
