---
- name: Include Vaulted Variables
  include_vars: vault.yml
  tags:
    - always

- name: Install VSCode
  import_tasks: vscode.yml
  tags:
    - install-code
    - install

- name: Install Extensions
  import_tasks: extensions.yml
  tags:
    - install-extensions
    - install

- name: Cleanup Files on Target Host
  import_tasks: cleanup.yml
  tags:
    - cleanup
    - install
