---
- name: "Install Required Playwright Package Dependencies"
  dnf:
    name:
      - pip
    state: present
  tags:
    - always

- name: "Copy VSCode rpm and Playwright extension to target host"
  copy:
    src: "{{ item }}"
    dest: /tmp
  loop:
    - "{{ vscode_rpm }}"
    - "{{ playwright_extension }}"
  tags:
    - install-vscode

- name: "Install VSCode rpm on target host"
  dnf:
    name: "/tmp/{{ vscode_rpm }}"
    state: present
    disable_gpg_check: true
  tags:
    - install-vscode

- name: "Install Playwright VSCode extension on target Host for target {{ extension_owner }} user"
  command: "code --install-extension /tmp/{{ playwright_extension }} --no-sandbox --user-data-dir=/tmp"
  become: true
  become_user: "{{ extension_owner }}"
  tags:
    - install-vscode

# - name: "Copy Python3.11 PIP Packages to Remote Host"
#   copy:
#     src: python311
#     dest: /tmp/
#     owner: root
#     group: root
