---
- name: "Install Required Playwright Package Dependencies"
  dnf:
    name:
      - pip
    state: present
  tags:
    - always

- name: "Copy VSCode rpm and Playwright extension to target host"
  copy:
    src: "{{ item }}"
    dest: /tmp
  loop:
    - "{{ vscode_rpm }}"
    - "{{ playwright_extension }}"
  tags:
    - install-vscode

- name: "Install VSCode rpm on target host"
  dnf:
    name: /tmp/code-1.76.2-1678817890.el7.x86_64.rpm
    state: present
    disable_gpg_check: true
  tags:
    - install-vscode

- name: "Install Playwright VSCode extension on target Host"
  command: "code --install-extension /tmp/{{ playwright_extension }} --no-sandbox --user-data-dir=/tmp"
  tags:
    - install-vscode

# - name: "Copy Python3.11 PIP Packages to Remote Host"
#   copy:
#     src: python311
#     dest: /tmp/
#     owner: root
#     group: root
